image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - fwcd.kotlin@0.2.10:kX3nrW3fv/LjU/QSQ41zYA==

tasks:
- before: |
    export PATH=$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$PATH
    mkdir -p /home/gitpod/.android
    touch /home/gitpod/.android/repositories.cfg
  init: |
    echo "Installing Android SDK..."
    mkdir -p /workspace/android-sdk && cd /workspace/android-sdk && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && unzip sdk-tools-linux-4333796.zip && rm -f sdk-tools-linux-4333796.zip
    /workspace/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
    echo "Download libgdx setup jar..."
    mkdir -p /workspace/libgdx && wget -P /workspace/libgdx/ https://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar